name: Build Debian Package

on: push

env:
  DEB_BUILD_OPTIONS: nocheck

jobs:
  build-artifact:
    runs-on: ubuntu-24-arm
    container:
     image: debian:bookworm

    steps:
      - uses: actions/checkout@master

      - name: Install container dependencies
        run: apt-get update -qq && apt -y install git sudo

      - name: Install Debian Package Building Dependencies
        run: sudo bash debian/install_pkg_build_deps.sh

      - name: Create Debian Package
        run: dpkg-buildpackage -b -rfakeroot -us -uc

      - name: Copy Debian Package to Artifact Directory
        run: cp ../*.deb .

      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@master
        with:
          name: artifact-deb
          path: ./*.deb

      - name: Upload Release Asset to GitHub
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.deb
